### PR TITLE
Add snazzy logo and rewrite base structure.

### LINKED ISSUE #3: Get logo with colored "O"
I think the current logo is pretty nice, but given the black background and white text, it might be nice to add some flare by using the redish "O" (like the one on the GitHub organization page) in place of the white O in ```logo.svg```.

Just a suggestion.

### PR DESCRIPTION
**Pull request by gmittal**
Closes #3. Because I didn't have push access and wanted to avoid a merge conflict I just created a new PR.

@jreinstra @jasonscharff: can you add some content so we can push to production?

### CODE REVIEW

**Comment by jreinstra** [comment]
@gmittal  Can you add screenshots of what this looks like?  It's hard for me to review this otherwise.

**Comment by jreinstra** [comment]
Also will help me determine what content we need.

**Comment by jasonscharff** [comment]
@jreinstra Just download the repo from Gautam's branch and then you can browse it a bit.

**Comment by jreinstra** [comment]
@jasonscharff  so I'm fine doing this now since it's the first big change but in the future it'll probably be faster for me to review things if there are just screenshots along with the PR (if we want to keep doing code review, which is another discussion)

@gmittal it looks good overall - nice work!  I'm working on a totality blog post tonight and Jason and I can work together on determining the content soon.  In the meantime, a few small things:

1. When I load the page I don't get a favicon.  Maybe make sure this is working properly?
2. I'd prefer you replace the blue "stay tuned" button + blue headers with the pink color from our logo.
3. I'd like our logo and the text right below it to be a bit larger.
4. Nix the PennApps logo at the bottom lol - also make sure we're not plagiarizing excessively from a PennApps landing page
5. Add some filler text for a slogan / motto right below the logo on the website
6. Consider making the text in the body of the page larger - we probably want to keep the text fairly short and more easier readable

**Review by jreinstra — DISMISSED** [review]
see comments above

**Comment by gmittal** [comment]
@jreinstra, would you like me to add a blog feature to this site? I wrote a very simple static blog generator for my own website with 50 lines of Node code that converts the markdown into HTML and adds them to the front page. I'm less familiar with jekyll, but if you want we can try and set that up too.

**Comment by jreinstra** [comment]
@gmittal  I don't think you need to worry about a blog feature - I was planning on putting it on medium anyway - but thanks for offering

**Comment by gmittal** [comment]
@jasonscharff @jreinstra PTAL?

**Comment by jreinstra** [comment]
@jasonscharff  can you take a look and start thinking about the content we want?

**Comment by jasonscharff** [comment]
@jreinstra On my to-do list for tonight.

**Comment by jasonscharff** [comment]
@gmittal Let's create a new branch for the re-factor and not push into master until this is done so we keep something else in the meantime. I'd close this PR and create a new one into a new branch.

**Comment by gmittal** [comment]
Ok, I changed the base branch to refactor, if it's good to merge I'll go ahead and do so.
@jasonscharff

**Comment by jasonscharff** [comment]
@gmittal Go ahead and merge for the sake of the fact that I think it's ridiculous to keep this in a long PR, but there are some changes I think:

1. Not a huge fan of the font. I think the logo goes for cleaner sort of look, but the font and the dollar sign in front of the sections looks more "code like." I prefer the cleaner look. The font in the logo is Ubuntu from google fonts. Love the new white logo with red sun BTW.
2. I'd like to add some sort of navigation bar as it could get difficult to follow with real content
3. Add a sponsor section––For now I'll just add something like for info on sponsoring email sponsor@totalityhacks.com
4. The copyright should actually be "Hackathon Organizers, LLC"
5. I think we should shrink the footer––and not have links to things that don't exist.
6. I'd like more distinction between the sections through different backgrounds or something. It can get hard to read in long form.

I'll start working on that content so dw about that.

**Comment by gmittal** [comment]
@jasonscharff, I'll file this as an issue so I can take care of it in the next PR.

**Pull request merged**
